/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        XBox: typeof import('@pkgs/ui')['XBox'];
        XButton: typeof import('@pkgs/ui')['XButton'];
        XIcon: typeof import('@pkgs/ui')['XIcon'];
        XMarkdown: typeof import('@pkgs/ui')['XMarkdown'];
        XMenu: typeof import('@pkgs/ui')['XMenu'];
        XPopupr: typeof import('@pkgs/ui')['XPopupr'];
        XRain: typeof import('@pkgs/ui')['XRain'];
    }
}
